import logging
import requests
import json

import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    user_id_list = []
    user_status_list = []

    api_key = 'eyJ0eXAiOiJKV1QiLCJub25jZSI6Im5NSTNSajZKR294QkR1d09rTFRQZVZ2WjByZzBVTEJUYmZmMzJsekNsTUkiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mM2I2ZGIxNC1hODlkLTQ3MWEtYTViNy05NzQwY2I2YzAwNzUvIiwiaWF0IjoxNjIxNzE0NTEwLCJuYmYiOjE2MjE3MTQ1MTAsImV4cCI6MTYyMTcxODQxMCwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiRTJaZ1lNZ3EwL01VK1hQS1B1djVKSllmMHlKbUpHM1k1em14bW5sMTdMSVpaZm94MDhVQiIsImFtciI6WyJwd2QiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggZXhwbG9yZXIgKG9mZmljaWFsIHNpdGUpIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNC4xMzguNzcuNDUiLCJuYW1lIjoi6rmA7Iuc7ZiEIiwib2lkIjoiNTFkYmJiZjktYzEwOC00NTM5LWJlZjAtZWU3MGYxZjA4M2YwIiwicGxhdGYiOiI1IiwicHVpZCI6IjEwMDMyMDAxMUNBQzYyQ0IiLCJyaCI6IjAuQVZRQUZOdTI4NTJvR2tlbHQ1ZEF5MndBZGJYSWk5NzUyYkZJcUsyM1NOcHlVR1JVQUtFLiIsInNjcCI6IkNhbGVuZGFycy5SZWFkIENhbGVuZGFycy5SZWFkV3JpdGUgb3BlbmlkIFByZXNlbmNlLlJlYWQgUHJlc2VuY2UuUmVhZC5BbGwgcHJvZmlsZSBVc2VyLlJlYWQgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoicHVkZloySHIwTEZWMzZvUHBubWVQR0VlUnRBRGdoSUpJTm4wUTV4QWpxUSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6ImYzYjZkYjE0LWE4OWQtNDcxYS1hNWI3LTk3NDBjYjZjMDA3NSIsInVuaXF1ZV9uYW1lIjoia3NoNzA3MjZAbzM2NS5odWZzLmFjLmtyIiwidXBuIjoia3NoNzA3MjZAbzM2NS5odWZzLmFjLmtyIiwidXRpIjoiLXFVZFZjZ3drMGVLVkMwNFRGRVpBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJIYjBfWUVNQ3o3RGU3RkVvcVRCcjJNREhPODBjWFdxVjVzZ2hENC1IYW1FIn0sInhtc190Y2R0IjoxNDQxMTc0NjYzfQ.dS9MdY7YQEfM8O15GKkcuDmCsv-30YJajM-1YCakE0wSnh9G_HI7fYF1lgPXi1aLoDPlBJktQG3eWFlq26Opyk-LYhyE0otdw4WQA6yDgSj2tdrDykDGLIk_380VEClVaXzx3wa0DOFDPDJ5wXAc4I4p71RmImkZXtAe-ti4yodI7ikz8XP-_5t3Y5wSU6hfmn8OfV46Ui98jOtavZXOpvGVS8ISW2qNKwDQbo5s-q-cJXQ6jxHgSdUUfndjTwhFGBubuVI7RgjItKJWKHylip8lN2JmTBfE7yiKOOGCohEFW1ew1m_E7yNf1mJpkrMupJ-Gba0GRXnly6rtEFFStA'
    user_request_url = 'https://graph.microsoft.com/v1.0/users?$select=id'


    request_header = {
        'Authorization': f'Bearer {api_key}',
    }

    user_id_response = requests.get(user_request_url, headers=request_header).json()

    for d in user_id_response.get('value'):
        user_id_list.append(d['id'])
        
    for i in user_id_list:
        user_status_list.append(requests.get(f'https://graph.microsoft.com/v1.0/users/{i}/presence', headers=request_header).json()['id'])

    return json.dumps(user_status_list)