import logging
import requests
import json

import azure.functions as func

api_key = 'eyJ0eXAiOiJKV1QiLCJub25jZSI6IkJjM3lwd2RqRW82M0lZUVBNUzhTc0Z5X1dZejVFX3dRckptRy1jUjNPN0EiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mM2I2ZGIxNC1hODlkLTQ3MWEtYTViNy05NzQwY2I2YzAwNzUvIiwiaWF0IjoxNjIxNzA3MDQ5LCJuYmYiOjE2MjE3MDcwNDksImV4cCI6MTYyMTcxMDk0OSwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiRTJaZ1lKajkxVnVzaFlQaGJNZWR1bWdGTzAxUnYrbXZhNHhxcnVaVkpUMWhjcGcyNFNFQSIsImFtciI6WyJwd2QiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggZXhwbG9yZXIgKG9mZmljaWFsIHNpdGUpIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNC4xMzguNzcuNDUiLCJuYW1lIjoi6rmA7Iuc7ZiEIiwib2lkIjoiNTFkYmJiZjktYzEwOC00NTM5LWJlZjAtZWU3MGYxZjA4M2YwIiwicGxhdGYiOiI1IiwicHVpZCI6IjEwMDMyMDAxMUNBQzYyQ0IiLCJyaCI6IjAuQVZRQUZOdTI4NTJvR2tlbHQ1ZEF5MndBZGJYSWk5NzUyYkZJcUsyM1NOcHlVR1JVQUtFLiIsInNjcCI6IkNhbGVuZGFycy5SZWFkIENhbGVuZGFycy5SZWFkV3JpdGUgb3BlbmlkIFByZXNlbmNlLlJlYWQgUHJlc2VuY2UuUmVhZC5BbGwgcHJvZmlsZSBVc2VyLlJlYWQgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoicHVkZloySHIwTEZWMzZvUHBubWVQR0VlUnRBRGdoSUpJTm4wUTV4QWpxUSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6ImYzYjZkYjE0LWE4OWQtNDcxYS1hNWI3LTk3NDBjYjZjMDA3NSIsInVuaXF1ZV9uYW1lIjoia3NoNzA3MjZAbzM2NS5odWZzLmFjLmtyIiwidXBuIjoia3NoNzA3MjZAbzM2NS5odWZzLmFjLmtyIiwidXRpIjoiMVFRSERKVGZwRWlGaVBlMU0wMzdBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJIYjBfWUVNQ3o3RGU3RkVvcVRCcjJNREhPODBjWFdxVjVzZ2hENC1IYW1FIn0sInhtc190Y2R0IjoxNDQxMTc0NjYzfQ.E2eZq-mHrqXyxcj8tJZ99whIDz5oeadBgl9UuGwQHkMyvVaNCgo0E6ImjA2JjECRDWQNpIjV0t6PDal_FkqIfsT13bUnXNNyZ9LCyTIevxT8xpEz5Lz32a2VbcXe1XeH8vSCxIEqa065J5CKU9YXgdZzSrxsGNDXVhZ07XkVZ2jUzNzXlvM8sDEQnDlONzx7U3tu82N0xrfY-4f82iVr_o9Vn0ACgTn1B5KgkgYyJusI6Tnef7Ol2Xt58JVuJKp_LiU59Rzxr2rwrlzZgl9NH7Tvni6ou304UwYY87qN2lmsxB-LXBo_U4dN2fnjnBc0bpD6HdoiKoiYCOZ8VD0gcA'

user_request_url = 'https://graph.microsoft.com/v1.0/users?$select=displayName, id'

request_header = {
    'Authorization': f'Bearer {api_key}',
}

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    user_id = req.params.get('user_id')
    status_request_url = f'https://graph.microsoft.com/beta/users/{user_id}/presence'
    
    if user_id:
        return json.dumps(requests.get(status_request_url, headers=request_header).json())
    else:
        return json.dumps(requests.get(user_request_url, headers=request_header).json())
